"""empty message

Revision ID: 0eb20b86aacf
Revises: f25d834d2b7c
Create Date: 2019-08-16 04:28:55.544737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb20b86aacf'
down_revision = 'f25d834d2b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'passports',
        sa.Column('id', sa.String(length=60), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('user_id', sa.String(length=60), nullable=False),
        sa.Column('passport_type', sa.String(length=60), nullable=False),
        sa.Column('nationality', sa.String(length=60), nullable=False),
        sa.Column('passport_no', sa.String(length=60), nullable=False),
        sa.Column('date_of_birth', sa.DateTime(), nullable=False),
        sa.Column('sex', sa.Enum(
            'male', 'female', name='sexenum'), nullable=False),
        sa.Column('date_of_issue', sa.DateTime(), nullable=False),
        sa.Column('date_of_expiry', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f(
            'passports_user_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_passports'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passports')
    op.execute("DROP TYPE sexenum")
    # ### end Alembic commands ###
