"""empty message

Revision ID: 7884b27e8339
Revises: d0a22cc5b56f
Create Date: 2019-09-02 10:40:32.540448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7884b27e8339'
down_revision = 'd0a22cc5b56f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'flights',
        sa.Column('id', sa.String(length=60), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('flight', sa.String(length=60), nullable=False),
        sa.Column('check_in', sa.DateTime(), nullable=False),
        sa.Column('departure', sa.DateTime(), nullable=False),
        sa.Column('airplane_id', sa.String(length=60), nullable=False),
        sa.Column('destination', sa.String(length=60), nullable=False),
        sa.Column('status', sa.Enum(
            'scheduled', 'departed', 'arrived', 'delayed',
            name='flightstatusenum'),
            server_default='scheduled', nullable=False),
        sa.ForeignKeyConstraint(['airplane_id'], ['airplanes.id'], name=op.f(
            'flights_airplane_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_flights'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.execute("DROP TYPE flightstatusenum")
    # ### end Alembic commands ###
